{
    $Id: set.inc,v 1.1.2.3 2001/06/25 02:32:58 carl Exp $
    This file is part of the Free Pascal run time library.
    Copyright (c) 1999-2001 by Carl-Eric Codere,
    member of the Free Pascal development team.

    See the file COPYING.FPC, included in this distribution,
    for details about the copyright.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 **********************************************************************}

{
  $Log: set.inc,v $
  Revision 1.1.2.3  2001/06/25 02:32:58  carl
  - removed unused stuff

  Revision 1.1.2.2  2001/06/22 13:11:53  pierre
   * sets as arrays of longints

  Revision 1.1.2.1  2001/05/09 03:31:42  carl
  * major cleanup, removed all asm routines

  Revision 1.1  2000/07/13 06:30:57  michael
  + Initial import

  Revision 1.8  2000/01/07 16:41:43  daniel
    * copyright 2000

  Revision 1.7  2000/01/07 16:32:29  daniel
    * copyright 2000 added

  Revision 1.6  1998/07/30 12:16:29  carl
    * set_sub_sets bugfix, was not using correct operation

  Revision 1.5  1998/07/01 14:27:13  carl
    * set_set and set_in bugfix

  Revision 1.2  1998/03/27 23:47:35  carl
    * bugfix of FLAGS as return values for SET_IN_BYTE and SET_SET_BYTE

  Revision 1.4  1998/01/26 12:01:42  michael
  + Added log at the end


}
