#
#   Makefile.fpc for Free Pascal Runtime Library
#

[package]
name=rtl
version=1.0.8

[require]
nortl=y

[target]
dirs_linux=linux
dirs_win32=win32
dirs_go32v2=go32v2
dirs_go32v1=go32v1
dirs_openbsd=openbsd
dirs_os2=os2
dirs_freebsd=freebsd
dirs_netbsd=netbsd
dirs_beos=beos
dirs_amiga=amiga
dirs_sunos=sunos
dirs_qnx=qnx

[install]
fpcpackage=y
createpackagefpc=y

[default]
fpcdir=..
